version: '3.4'

services:
  pythonfastapi:
    image: pythonfastapi
    build:
      context: ./PythonFastApi/
      dockerfile: ./PythonFastApi/Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && cd PythonFastApi && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn main:app --host 0.0.0.0 --port 8811"]
    ports:
      - 8811:8811
      - 5678:5678
